title: Lakshay Gupta
logo: "/IMG_20230701_121750.jpg"
description: >
  <br>
  Software Engineer | FullStack Engineer
  <br>
  <a href="http://www.linkedin.com/in/lakshay-gupta-3284311b2">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:lakshaygupta3110@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
  <br>
  Contact: ðŸ“§ lakshaygupta3110@gmail.com | ðŸ“ž 9818696017
  <br>
theme: jekyll-theme-minimal
